version: '3.8'

services:
  our_notes_mysql:
    image: mysql:8.0
    container_name: our_notes_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: our_notes_user
      MYSQL_PASSWORD: our_notes_password
    ports:
      - "8383:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: our_notes_mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - our_notes_mysql
    networks:
      - mysql_network

volumes:
  mysql_data:

networks:
  mysql_network: